/**
 * scene-loader/ — Declarative scene loading from YAML/JSON files (spec 022)
 * ────────────────────────────────────────────────────────────────────────────
 * Provides `loadSceneFile(filePath)` which reads a `.yaml`, `.yml`, or `.json`
 * file, parses it, validates it against the JSON Schema (`sceneDefinitionSchema`
 * from `@evol-hive/shared`), auto-generates doorway objects for rooms with
 * connections but no explicit doorway, and returns a `SceneDefinition` that
 * can be passed directly to `loadScene(core, scene)`.
 *
 * When validation fails, a `SceneValidationError` is thrown with the file path,
 * a list of human-readable validation errors (JSON Pointer paths + messages),
 * and the raw parsed object for debugging.
 */

import { readFileSync } from 'node:fs';
import { extname } from 'node:path';
import * as yaml from 'js-yaml';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import type { SceneDefinition, SmartObject, Affordance } from '@evol-hive/shared';
import { sceneDefinitionSchema } from '@evol-hive/shared';

// Re-export handler-plugin system for convenience.
export {
  type HandlerPlugin,
  registerHandlerPlugin,
  clearHandlerPlugins,
  getRegisteredPlugins,
  autoRegisterHandlers,
  createBuiltinPlugins,
} from './handler-plugins.js';

// ─── SceneValidationError ───────────────────────────────────────────────────

/** A single validation issue from the JSON Schema validator. */
export interface SceneValidationIssue {
  /** JSON Pointer path to the invalid field (e.g., "/rooms/0/name"). */
  instancePath: string;
  /** JSON Schema path to the violated keyword (e.g., "/properties/rooms/items/required"). */
  schemaPath: string;
  /** Human-readable error message. */
  message: string;
  /** The AJV keyword that failed (e.g., "required", "type"). */
  keyword: string;
}

/**
 * Thrown when a scene file fails JSON Schema validation (spec 022, Req 8).
 * Includes the file path, a list of human-readable validation errors with
 * JSON Pointer paths, and the raw parsed object for debugging.
 */
export class SceneValidationError extends Error {
  readonly filePath: string;
  readonly errors: readonly SceneValidationIssue[];
  readonly rawObject: unknown;

  constructor(filePath: string, errors: SceneValidationIssue[], rawObject: unknown) {
    const messages = errors.map((e) => `  ${e.instancePath || '/'}: ${e.message}`).join('\n');
    super(`Scene validation failed for ${filePath}:\n${messages}`);
    this.name = 'SceneValidationError';
    this.filePath = filePath;
    this.errors = errors;
    this.rawObject = rawObject;
  }
}

// ─── Validator setup ────────────────────────────────────────────────────────

let _ajv: Ajv2020 | null = null;

function getValidator(): Ajv2020 {
  if (_ajv !== null) return _ajv;
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  addFormats(ajv);
  ajv.addSchema(sceneDefinitionSchema as Record<string, unknown>);
  _ajv = ajv;
  return ajv;
}

// ─── validateSceneObject ────────────────────────────────────────────────────

/**
 * Validate a raw parsed object against the SceneDefinition JSON Schema
 * (spec 022, Req 5). Returns a typed `SceneDefinition` on success.
 *
 * @param obj - The parsed YAML/JSON object to validate.
 * @param filePath - Optional file path for error messages.
 * @throws {SceneValidationError} when validation fails.
 */
export function validateSceneObject(obj: unknown, filePath: string = '<inline>'): SceneDefinition {
  const ajv = getValidator();
  const validate = ajv.getSchema('https://evol-hive.dev/schemas/scene-definition.json')!;

  if (!validate(obj)) {
    const errors: SceneValidationIssue[] = (validate.errors ?? []).map((err) => ({
      instancePath: err.instancePath,
      schemaPath: err.schemaPath,
      message: err.message ?? 'Validation error',
      keyword: err.keyword,
    }));
    throw new SceneValidationError(filePath, errors, obj);
  }

  return obj as SceneDefinition;
}

// ─── Doorway auto-generation ─────────────────────────────────────────────────

/**
 * Auto-generate doorway smart objects for rooms that have `connections` but
 * no explicit doorway object in their `objectIds` (spec 022, Req 12).
 *
 * The generated doorway object has:
 *   - `id`: `doorway-<roomId>`
 *   - `type`: `"doorway"`
 *   - `roomId`: the room's ID
 *   - `affordances`: one `go_to_<connectionId>` affordance per connection
 *
 * If a doorway object already exists in the scene (matching `doorway-<roomId>`),
 * it is not duplicated.
 */
export function autoGenerateDoorways(scene: SceneDefinition): SceneDefinition {
  const existingDoorwayIds = new Set(
    scene.objects.filter((o) => o.type === 'doorway').map((o) => o.id),
  );

  const generatedDoorways: SmartObject[] = [];

  for (const room of scene.rooms) {
    if (room.connections.length === 0) continue;
    const doorwayId = `doorway-${room.id}`;
    if (existingDoorwayIds.has(doorwayId)) continue;

    // Check if a doorway is already listed in this room's objectIds
    if (room.objectIds.includes(doorwayId)) continue;

    const affordances: Affordance[] = room.connections.map((conn) => ({
      id: `go_to_${conn}`,
      label: `Go to ${conn}`,
      engineEffect: `go_to_${conn}`,
      preconditions: [],
      effects: {},
    }));

    generatedDoorways.push({
      id: doorwayId,
      name: 'Doorway',
      type: 'doorway',
      state: {},
      affordances,
      roomId: room.id,
    });
  }

  if (generatedDoorways.length === 0) return scene;

  return {
    ...scene,
    objects: [...scene.objects, ...generatedDoorways],
  };
}

// ─── loadSceneFile ──────────────────────────────────────────────────────────

/**
 * Load and validate a scene definition file (spec 022, Req 7).
 *
 * Reads a `.yaml`, `.yml`, or `.json` file, parses it, validates it against the
 * JSON Schema, auto-generates doorway objects, and returns a `SceneDefinition`
 * compatible with `loadScene(core, scene)`.
 *
 * @param filePath - Path to the scene file (`.yaml`, `.yml`, or `.json`).
 * @returns A validated `SceneDefinition` with auto-generated doorways.
 * @throws {SceneValidationError} when validation fails.
 * @throws {Error} when the file cannot be read or parsed.
 */
export async function loadSceneFile(filePath: string): Promise<SceneDefinition> {
  const ext = extname(filePath).toLowerCase();

  // Read file
  let raw: string;
  try {
    raw = readFileSync(filePath, 'utf-8');
  } catch (err) {
    throw new Error(`Cannot read scene file: ${filePath} — ${(err as Error).message}`, {
      cause: err,
    });
  }

  // Parse based on extension
  let parsed: unknown;
  try {
    if (ext === '.json') {
      parsed = JSON.parse(raw);
    } else if (ext === '.yaml' || ext === '.yml') {
      parsed = yaml.load(raw);
    } else {
      throw new Error(`Unsupported file extension "${ext}". Use .yaml, .yml, or .json.`);
    }
  } catch (err) {
    if (err instanceof SceneValidationError) throw err;
    throw new Error(`Cannot parse scene file ${filePath}: ${(err as Error).message}`, {
      cause: err,
    });
  }

  // Validate against JSON Schema
  const scene = validateSceneObject(parsed, filePath);

  // Auto-generate doorways
  const sceneWithDoorways = autoGenerateDoorways(scene);

  return sceneWithDoorways;
}
