/**
 * Spec 022 implementation tests — Scene Authoring (Declarative)
 * ===============================================================
 * Tests for the scene loader, JSON Schema validation, handler plugin
 * system, and doorway auto-generation. These tests cover AC-1 through
 * AC-11, AC-16, and AC-19 from the spec.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { SceneDefinition } from '@evol-hive/shared';
import { createEngineCore, loadScene, type EngineCore } from '../src/assembly.js';

// ─── Imports under test (will be implemented) ──────────────────────────────
// These imports will fail until the implementation is written — that's TDD.
import {
  SceneValidationError,
  loadSceneFile,
  validateSceneObject,
  autoGenerateDoorways,
} from '../src/scene-loader/index.js';
import {
  registerHandlerPlugin,
  clearHandlerPlugins,
  getRegisteredPlugins,
  autoRegisterHandlers,
  createBuiltinPlugins,
  type HandlerPlugin,
} from '../src/scene-loader/handler-plugins.js';

// ─── Test fixtures ───────────────────────────────────────────────────────────

const REPO_ROOT = resolve(__dirname, '../../..');
const TMP_DIR = join(REPO_ROOT, 'packages/engine/tests/tmp-scene-files');

function ensureTmpDir(): void {
  if (existsSync(TMP_DIR)) rmSync(TMP_DIR, { recursive: true });
  mkdirSync(TMP_DIR, { recursive: true });
}

function cleanupTmpDir(): void {
  if (existsSync(TMP_DIR)) rmSync(TMP_DIR, { recursive: true });
}

/** A minimal valid scene YAML. */
const VALID_YAML = `
id: test-scene
name: Test Scene
rooms:
  - id: living_room
    name: Living Room
    description: A cozy living room.
    connections:
      - kitchen
    objectIds:
      - sofa-1
  - id: kitchen
    name: Kitchen
    description: A kitchen.
    connections:
      - living_room
    objectIds:
      - fridge-1
objects:
  - id: sofa-1
    name: Sofa
    type: furniture
    state:
      cushions: 3
    roomId: living_room
    affordances:
      - id: relax
        label: Relax on the sofa
        engineEffect: relax
        preconditions: []
        effects:
          comfort: 20
          energy: 5
  - id: fridge-1
    name: Fridge
    type: appliance
    state:
      temperature: 4
    roomId: kitchen
    affordances:
      - id: get_food
        label: Get food from fridge
        engineEffect: get_food
        preconditions:
          - has_food
        effects:
          hunger: -20
        conditions:
          - field: temperature
            operator: '>'
            value: 0
        stepGroup: eat_sequence
        stepOrder: 1
    stateRules:
      - field: temperature
        operation: approach
        rate: 0.5
        target: 4
        interval: 2
    compoundActions:
      - id: eat_sequence
        label: Eat food from the fridge
        steps:
          - affordanceId: get_food
            description: Get food
    dependencies:
      - affordanceId: get_food
        requiresObjectId: door-1
        requiresAffordance: open_door
        description: Open the door first
agents:
  - id: agent-alice
    name: Alice
    description: A test agent.
    traits:
      - curious
    initialDrives:
      energy: 50
      hunger: 30
    backstory: Alice is a test agent.
    longTermGoals:
      - Explore the world
    behavioralTendencies:
      - curious
    speechStyle: casual and witty
    relationships:
      agent-bob: A close friend
    startRoomId: living_room
`;

/** A valid JSON scene. */
const VALID_JSON = JSON.stringify({
  id: 'json-scene',
  name: 'JSON Scene',
  rooms: [
    {
      id: 'room-1',
      name: 'Room One',
      description: 'First room.',
      connections: [],
      objectIds: [],
    },
  ],
  objects: [],
  agents: [],
});

/** A malformed YAML with missing required field (no name on room). */
const MALFORMED_YAML = `
id: bad-scene
name: Bad Scene
rooms:
  - id: room-1
    description: Missing name field.
    connections: []
    objectIds: []
objects: []
agents: []
`;

/** A YAML with doorway auto-generation test data. */
const DOORWAY_YAML = `
id: doorway-scene
name: Doorway Scene
rooms:
  - id: living_room
    name: Living Room
    description: Living room with a connection to kitchen.
    connections:
      - kitchen
    objectIds: []
  - id: kitchen
    name: Kitchen
    description: Kitchen connected to living room.
    connections:
      - living_room
    objectIds: []
objects: []
agents: []
`;

// ─── Schema validation tests (AC-1 through AC-4) ───────────────────────────

describe('Spec 022 — AC-1: JSON Schema file exists', () => {
  it('scene-schema.json exists at packages/shared/src/schemas/scene-schema.json', () => {
    const schemaPath = join(REPO_ROOT, 'packages/shared/src/schemas/scene-schema.json');
    expect(existsSync(schemaPath)).toBe(true);
  });

  it('scene-schema.json is a valid Draft 2020-12 JSON Schema', () => {
    const schemaPath = join(REPO_ROOT, 'packages/shared/src/schemas/scene-schema.json');
    const schema = JSON.parse(require('node:fs').readFileSync(schemaPath, 'utf-8'));
    expect(schema['$schema']).toBe('https://json-schema.org/draft/2020-12/schema');
    expect(schema.type).toBe('object');
    expect(schema.properties.rooms).toBeDefined();
    expect(schema.properties.objects).toBeDefined();
    expect(schema.properties.agents).toBeDefined();
  });

  it('validateSceneObject accepts a valid SceneDefinition structure', () => {
    const obj = yaml.load(VALID_YAML);
    const scene = validateSceneObject(obj);
    expect(scene.id).toBe('test-scene');
    expect(scene.rooms).toHaveLength(2);
    expect(scene.objects).toHaveLength(2);
    expect(scene.agents).toHaveLength(1);
  });
});

describe('Spec 022 — AC-2: Room schema validation', () => {
  it('a YAML file with rooms containing id, name, description, connections, objectIds passes validation', () => {
    const obj = yaml.load(VALID_YAML);
    const scene = validateSceneObject(obj);
    const room = scene.rooms[0]!;
    expect(room.id).toBe('living_room');
    expect(room.name).toBe('Living Room');
    expect(room.description).toBe('A cozy living room.');
    expect(room.connections).toEqual(['kitchen']);
    expect(room.objectIds).toEqual(['sofa-1']);
  });
});

describe('Spec 022 — AC-3: Object schema validation (with stateRules, compoundActions, dependencies, conditions)', () => {
  it('a YAML file with full object definition passes schema validation', () => {
    const obj = yaml.load(VALID_YAML);
    const scene = validateSceneObject(obj);
    const obj2 = scene.objects[1]!;
    expect(obj2.id).toBe('fridge-1');
    expect(obj2.name).toBe('Fridge');
    expect(obj2.type).toBe('appliance');
    expect(obj2.roomId).toBe('kitchen');
    expect(obj2.state).toEqual({ temperature: 4 });
    // Affordance with conditions, stepGroup, stepOrder
    const aff = obj2.affordances[0]!;
    expect(aff.id).toBe('get_food');
    expect(aff.label).toBe('Get food from fridge');
    expect(aff.engineEffect).toBe('get_food');
    expect(aff.preconditions).toEqual(['has_food']);
    expect(aff.effects).toEqual({ hunger: -20 });
    expect(aff.conditions).toEqual([{ field: 'temperature', operator: '>', value: 0 }]);
    expect(aff.stepGroup).toBe('eat_sequence');
    expect(aff.stepOrder).toBe(1);
    // stateRules
    expect(obj2.stateRules).toHaveLength(1);
    expect(obj2.stateRules![0]).toEqual({
      field: 'temperature',
      operation: 'approach',
      rate: 0.5,
      target: 4,
      interval: 2,
    });
    // compoundActions
    expect(obj2.compoundActions).toHaveLength(1);
    expect(obj2.compoundActions![0].id).toBe('eat_sequence');
    // dependencies
    expect(obj2.dependencies).toHaveLength(1);
    expect(obj2.dependencies![0].affordanceId).toBe('get_food');
  });
});

describe('Spec 022 — AC-4: Agent schema validation', () => {
  it('a YAML file with full agent definition passes schema validation', () => {
    const obj = yaml.load(VALID_YAML);
    const scene = validateSceneObject(obj);
    const agent = scene.agents[0]!;
    expect(agent.id).toBe('agent-alice');
    expect(agent.name).toBe('Alice');
    expect(agent.description).toBe('A test agent.');
    expect(agent.traits).toEqual(['curious']);
    expect(agent.initialDrives).toEqual({ energy: 50, hunger: 30 });
    expect(agent.backstory).toBe('Alice is a test agent.');
    expect(agent.longTermGoals).toEqual(['Explore the world']);
    expect(agent.behavioralTendencies).toEqual(['curious']);
    expect(agent.speechStyle).toBe('casual and witty');
    expect(agent.relationships).toEqual({ 'agent-bob': 'A close friend' });
    expect(agent.startRoomId).toBe('living_room');
  });
});

// ─── Scene loader tests (AC-5 through AC-8) ────────────────────────────────

describe('Spec 022 — AC-5: loadSceneFile returns SceneDefinition from YAML', () => {
  let tmpFile: string;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'test-scene.yaml');
    writeFileSync(tmpFile, VALID_YAML, 'utf-8');
  });

  afterEach(cleanupTmpDir);

  it('loadSceneFile("path/to/scene.yaml") returns a SceneDefinition matching the YAML content', async () => {
    const scene = await loadSceneFile(tmpFile);
    expect(scene.id).toBe('test-scene');
    expect(scene.name).toBe('Test Scene');
    expect(scene.rooms).toHaveLength(2);
    expect(scene.rooms[0]!.id).toBe('living_room');
    // 2 original objects + 2 auto-generated doorways (each room has connections)
    expect(scene.objects).toHaveLength(4);
    expect(scene.objects[0]!.id).toBe('sofa-1');
    expect(scene.agents).toHaveLength(1);
    expect(scene.agents[0]!.id).toBe('agent-alice');
  });
});

describe('Spec 022 — AC-6: loadSceneFile returns SceneDefinition from JSON', () => {
  let tmpFile: string;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'test-scene.json');
    writeFileSync(tmpFile, VALID_JSON, 'utf-8');
  });

  afterEach(cleanupTmpDir);

  it('loadSceneFile("path/to/scene.json") returns a valid SceneDefinition', async () => {
    const scene = await loadSceneFile(tmpFile);
    expect(scene.id).toBe('json-scene');
    expect(scene.name).toBe('JSON Scene');
    expect(scene.rooms).toHaveLength(1);
    expect(scene.rooms[0]!.id).toBe('room-1');
  });

  it('loadSceneFile supports .yml extension too', async () => {
    const ymlFile = join(TMP_DIR, 'test-scene.yml');
    writeFileSync(ymlFile, VALID_YAML, 'utf-8');
    const scene = await loadSceneFile(ymlFile);
    expect(scene.id).toBe('test-scene');
  });
});

describe('Spec 022 — AC-7: SceneValidationError on missing required field', () => {
  let tmpFile: string;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'malformed-scene.yaml');
    writeFileSync(tmpFile, MALFORMED_YAML, 'utf-8');
  });

  afterEach(cleanupTmpDir);

  it('throws SceneValidationError with file path and JSON Pointer path', async () => {
    try {
      await loadSceneFile(tmpFile);
      expect.fail('Should have thrown SceneValidationError');
    } catch (err) {
      expect(err).toBeInstanceOf(SceneValidationError);
      const e = err as SceneValidationError;
      expect(e.filePath).toBe(tmpFile);
      expect(e.errors.length).toBeGreaterThan(0);
      // The error should reference /rooms/0/name (missing name)
      const errorStrings = e.errors.map((er) => er.instancePath + ': ' + er.message).join('\n');
      expect(errorStrings).toContain('/rooms/0');
      expect(errorStrings.toLowerCase()).toContain('name');
      // rawObject should be present for debugging
      expect(e.rawObject).toBeDefined();
    }
  });
});

describe('Spec 022 — AC-8: loadSceneFile output is compatible with loadScene', () => {
  let tmpFile: string;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'test-scene.yaml');
    writeFileSync(tmpFile, VALID_YAML, 'utf-8');
  });

  afterEach(cleanupTmpDir);

  it('SceneDefinition from loadSceneFile can be passed directly to loadScene', async () => {
    const scene = await loadSceneFile(tmpFile);
    const core = createEngineCore({
      fps: 60,
      spatialDebounceSeconds: 5,
      maxConcurrentLLM: 1,
    });
    // Should not throw — no adaptation needed
    loadScene(core, scene);
    expect(core.sceneManager.getRoom('living_room')).toBeDefined();
    expect(core.sceneManager.getRoom('kitchen')).toBeDefined();
    expect(core.smartObjectRegistry.get('sofa-1')).toBeDefined();
    expect(core.smartObjectRegistry.get('fridge-1')).toBeDefined();
    expect(core.agentManager.getState('agent-alice')).toBeDefined();
  });
});

// ─── Handler plugin system tests (AC-9, AC-10) ─────────────────────────────

describe('Spec 022 — AC-9: Affordance handler auto-registration', () => {
  let tmpFile: string;
  let core: EngineCore;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'test-scene.yaml');
    writeFileSync(tmpFile, VALID_YAML, 'utf-8');
    core = createEngineCore({
      fps: 60,
      spatialDebounceSeconds: 5,
      maxConcurrentLLM: 1,
    });
    clearHandlerPlugins();
    // Register built-in plugins that include handlers for 'relax' (furniture type)
    createBuiltinPlugins().forEach(registerHandlerPlugin);
  });

  afterEach(() => {
    cleanupTmpDir();
    clearHandlerPlugins();
  });

  it('after auto-registration, all affordances have registered engineEffect handlers', async () => {
    const scene = await loadSceneFile(tmpFile);
    loadScene(core, scene);
    autoRegisterHandlers(core, scene);

    // Check every affordance in the scene has a registered handler
    for (const obj of scene.objects) {
      for (const aff of obj.affordances) {
        const handler = core.affordanceRegistry.getHandler(aff.engineEffect);
        expect(handler, `Handler for "${aff.engineEffect}" should be registered`).not.toBeNull();
      }
    }
  });
});

describe('Spec 022 — AC-10: Custom HandlerPlugin for custom object type', () => {
  let tmpFile: string;
  let core: EngineCore;

  const CUSTOM_YAML = `
id: custom-scene
name: Custom Scene
rooms:
  - id: room-1
    name: Room One
    description: A room.
    connections: []
    objectIds:
      - device-1
objects:
  - id: device-1
    name: Custom Device
    type: custom_device
    state:
      power: 100
    roomId: room-1
    affordances:
      - id: activate
        label: Activate device
        engineEffect: activate
        preconditions: []
        effects:
          energy: 10
agents: []
`;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'custom-scene.yaml');
    writeFileSync(tmpFile, CUSTOM_YAML, 'utf-8');
    core = createEngineCore({
      fps: 60,
      spatialDebounceSeconds: 5,
      maxConcurrentLLM: 1,
    });
    clearHandlerPlugins();
  });

  afterEach(() => {
    cleanupTmpDir();
    clearHandlerPlugins();
  });

  it('custom HandlerPlugin for custom_device provides auto-registered handlers', async () => {
    const customPlugin: HandlerPlugin = {
      objectType: 'custom_device',
      handlers: {
        activate: async (_objId, _agentId, state) => ({
          success: true,
          newState: state,
          driveChanges: { energy: 10 },
        }),
      },
    };
    registerHandlerPlugin(customPlugin);

    const scene = await loadSceneFile(tmpFile);
    loadScene(core, scene);
    autoRegisterHandlers(core, scene);

    const handler = core.affordanceRegistry.getHandler('activate');
    expect(handler).not.toBeNull();
    const result = await handler!('device-1', 'agent-x', { power: 100 });
    expect(result.success).toBe(true);
  });
});

// ─── Doorway auto-generation tests (AC-11) ──────────────────────────────────

describe('Spec 022 — AC-11: Doorway auto-generation', () => {
  let tmpFile: string;

  beforeEach(() => {
    ensureTmpDir();
    tmpFile = join(TMP_DIR, 'doorway-scene.yaml');
    writeFileSync(tmpFile, DOORWAY_YAML, 'utf-8');
  });

  afterEach(cleanupTmpDir);

  it('auto-generates doorway objects for rooms with connections but no doorway', async () => {
    const scene = await loadSceneFile(tmpFile);
    // The original YAML had no objects, but doorways should be auto-generated
    expect(scene.objects.length).toBeGreaterThan(0);

    // Check for doorway-living_room with go_to_kitchen affordance
    const livingRoomDoorway = scene.objects.find((o) => o.id === 'doorway-living_room');
    expect(livingRoomDoorway).toBeDefined();
    expect(livingRoomDoorway!.type).toBe('doorway');
    expect(livingRoomDoorway!.roomId).toBe('living_room');
    const goToKitchen = livingRoomDoorway!.affordances.find((a) => a.id === 'go_to_kitchen');
    expect(goToKitchen).toBeDefined();
    expect(goToKitchen!.engineEffect).toBe('go_to_kitchen');

    // Check for doorway-kitchen with go_to_living_room affordance
    const kitchenDoorway = scene.objects.find((o) => o.id === 'doorway-kitchen');
    expect(kitchenDoorway).toBeDefined();
    const goToLivingRoom = kitchenDoorway!.affordances.find((a) => a.id === 'go_to_living_room');
    expect(goToLivingRoom).toBeDefined();
  });

  it('does not auto-generate doorway if doorway already exists in objectIds', async () => {
    const yamlWithExistingDoorway = `
id: existing-doorway-scene
name: Existing Doorway Scene
rooms:
  - id: room-a
    name: Room A
    description: Room A.
    connections:
      - room-b
    objectIds:
      - doorway-room-a
objects:
  - id: doorway-room-a
    name: Doorway
    type: doorway
    state: {}
    roomId: room-a
    affordances:
      - id: go_to_room-b
        label: Go to Room B
        engineEffect: go_to_room-b
        preconditions: []
        effects: {}
agents: []
`;
    const existingFile = join(TMP_DIR, 'existing-doorway.yaml');
    writeFileSync(existingFile, yamlWithExistingDoorway, 'utf-8');
    const scene = await loadSceneFile(existingFile);
    // Should still have exactly 1 doorway (not duplicated)
    const doorways = scene.objects.filter((o) => o.id === 'doorway-room-a');
    expect(doorways).toHaveLength(1);
  });
});

// ─── Example scene file tests (AC-16) ──────────────────────────────────────

describe('Spec 022 — AC-16: examples/coffee-shop.scene.yaml exists and is valid', () => {
  it('coffee-shop.scene.yaml exists', () => {
    const path = join(REPO_ROOT, 'examples/coffee-shop.scene.yaml');
    expect(existsSync(path)).toBe(true);
  });

  it('coffee-shop.scene.yaml loads as a valid SceneDefinition', async () => {
    const path = join(REPO_ROOT, 'examples/coffee-shop.scene.yaml');
    const scene = await loadSceneFile(path);
    expect(scene.id).toBe('coffee-shop');
    expect(scene.name).toBe('Coffee Shop');
    // Same rooms as coffee-shop.ts
    expect(scene.rooms.map((r) => r.id).sort()).toEqual(
      ['bathroom', 'garden', 'kitchen', 'living_room'].sort(),
    );
    // Same agents as coffee-shop.ts
    expect(scene.agents.map((a) => a.id).sort()).toEqual(
      ['agent-alice', 'agent-bob', 'agent-carol'].sort(),
    );
    // Should have the coffee machine object
    expect(scene.objects.find((o) => o.id === 'coffee-1')).toBeDefined();
  });
});

// ─── SceneDefinition interface unchanged (AC-19) ───────────────────────────

describe('Spec 022 — AC-19: SceneDefinition interface unchanged', () => {
  it('SceneDefinition has id, name, rooms, objects, agents — no new required fields', () => {
    // This is a compile-time check that the interface is unchanged.
    // If the interface changed, this file wouldn't compile.
    const scene: SceneDefinition = {
      id: 'x',
      name: 'x',
      rooms: [],
      objects: [],
      agents: [],
    };
    expect(scene.id).toBe('x');
  });
});

// ─── Plugin system utility tests ──────────────────────────────────────────

describe('Spec 022 — Handler plugin registry', () => {
  beforeEach(() => {
    clearHandlerPlugins();
  });

  afterEach(() => {
    clearHandlerPlugins();
  });

  it('registerHandlerPlugin adds a plugin retrievable via getRegisteredPlugins', () => {
    const plugin: HandlerPlugin = {
      objectType: 'test_type',
      handlers: {},
    };
    registerHandlerPlugin(plugin);
    const plugins = getRegisteredPlugins();
    expect(plugins.some((p) => p.objectType === 'test_type')).toBe(true);
  });

  it('clearHandlerPlugins removes all plugins', () => {
    registerHandlerPlugin({ objectType: 'test_type', handlers: {} });
    clearHandlerPlugins();
    expect(getRegisteredPlugins()).toHaveLength(0);
  });

  it('createBuiltinPlugins returns plugins for known object types', () => {
    const plugins = createBuiltinPlugins();
    expect(plugins.length).toBeGreaterThan(0);
    // Should include doorway type (for movement handlers)
    const types = plugins.map((p) => p.objectType);
    expect(types).toContain('doorway');
    // Should include furniture (relax, sit_outside, read_book)
    expect(types).toContain('furniture');
  });
});

// ─── Helper: YAML parse (for inline test data) ─────────────────────────────
// We use js-yaml here for parsing test fixtures inline.
import * as yaml from 'js-yaml';
